"use strict";
// PostgreSQL version for King Academy Student Registration System.
// Keep the original server.js (SQLite) as a rollback copy until this version is fully tested.
require("dotenv").config();
const express = require("express");
const session = require("express-session");
const pg = require("pg");
const multer = require("multer");
const path = require("path");
const fs = require("fs");
const app = express();
const { Pool } = pg;
const PORT = Number(process.env.PORT || 3000);
const ROOT = __dirname;
const uploadDir = process.env.UPLOAD_DIR || path.join(ROOT, "uploads");
fs.mkdirSync(uploadDir, { recursive: true });
if (!process.env.DATABASE_URL) {
  console.error(
    "DATABASE_URL is missing. Set it in .env locally or Render Environment.",
  );
  process.exit(1);
}
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl:
    process.env.PGSSLMODE === "disable" ? false : { rejectUnauthorized: false },
});

pool.on("error", (e) =>
  console.error("Unexpected PostgreSQL pool error:", e.message),
);

pool.on("error", (e) =>
  console.error("Unexpected PostgreSQL pool error:", e.message),
);

async function initDb() {
  await pool.query(`CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id TEXT UNIQUE NOT NULL, first_name TEXT NOT NULL, middle_name TEXT, last_name TEXT NOT NULL,
    gender TEXT NOT NULL, date_of_birth TEXT, grade TEXT NOT NULL, program TEXT, academic_year TEXT,
    admission_date TEXT, phone TEXT, email TEXT, address TEXT, guardian_name TEXT, guardian_phone TEXT,
    status TEXT NOT NULL DEFAULT 'Pending', photo TEXT, document TEXT, notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`);
  await pool.query(`CREATE TABLE IF NOT EXISTS activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, action TEXT NOT NULL, description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`);
  await pool.query(`CREATE TABLE IF NOT EXISTS subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`);
  await pool.query(`CREATE TABLE IF NOT EXISTS marks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    academic_year TEXT NOT NULL, grade TEXT NOT NULL, subject TEXT NOT NULL, score DOUBLE PRECISION NOT NULL DEFAULT 0,
    max_score DOUBLE PRECISION NOT NULL DEFAULT 100, remark TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(student_id, academic_year, subject)
  )`);
  // Additive compatibility for existing Neon tables; does not delete or reseed records.
  await pool.query(
    "ALTER TABLE students ADD COLUMN IF NOT EXISTS academic_year TEXT",
  );
  await pool.query(
    "ALTER TABLE students ADD COLUMN IF NOT EXISTS admission_date TEXT",
  );
  // Intentionally do not seed subjects or sample students during migration testing.
}
function currentAcademicYear() {
  const d = new Date();
  const y = d.getFullYear();
  const start = d.getMonth() >= 8 ? y : y - 1;
  return `${start}/${String(start + 1).slice(-2)}`;
}
function yearList() {
  const y = parseInt(currentAcademicYear(), 10);
  return [
    ...new Set([
      currentAcademicYear(),
      `${y - 1}/${String(y).slice(-2)}`,
      `${y - 2}/${String(y - 1).slice(-2)}`,
      "2025/26",
      "2024/25",
    ]),
  ];
}
function studentName(s) {
  return [s.first_name, s.middle_name, s.last_name].filter(Boolean).join(" ");
}
function gradeSortValue(g = "") {
  if (g.startsWith("KG ")) return Number(g.slice(3));
  return 4 + Number(g.replace("Grade ", ""));
}
async function log(action, description) {
  await pool.query(
    "INSERT INTO activity_logs(action,description) VALUES($1,$2)",
    [action, description],
  );
}
async function nextRegistrationId() {
  const year = new Date().getFullYear();
  const r = await pool.query(
    "SELECT registration_id FROM students WHERE registration_id LIKE $1 ORDER BY id DESC LIMIT 1",
    [`KA${year}%`],
  );
  const m = r.rows[0]?.registration_id?.match(/(\d{4})$/);
  const n = m ? Number(m[1]) + 1 : 1;
  return `KA${year}${String(n).padStart(4, "0")}`;
}
async function resultForStudent(studentId, academicYear) {
  const sr = await pool.query("SELECT * FROM students WHERE id=$1", [
    studentId,
  ]);
  const student = sr.rows[0];
  if (!student) return null;
  const mr = await pool.query(
    "SELECT * FROM marks WHERE student_id=$1 AND academic_year=$2 ORDER BY subject",
    [studentId, academicYear],
  );
  const marks = mr.rows;
  const total = marks.reduce((a, r) => a + Number(r.score), 0);
  const max_total = marks.reduce((a, r) => a + Number(r.max_score), 0);
  const average = max_total ? (total / max_total) * 100 : 0;
  return {
    student,
    academic_year: academicYear,
    marks,
    total,
    max_total,
    average: Number(average.toFixed(2)),
    subjects_count: marks.length,
    result: marks.length ? (average >= 50 ? "PASS" : "FAIL") : "NO MARKS",
  };
}
async function rankedResults(academicYear, grade) {
  const args = grade ? [grade] : [];
  const sql = `SELECT * FROM students ${grade ? "WHERE grade=$1" : ""} ORDER BY grade, last_name, first_name`;
  const students = (await pool.query(sql, args)).rows;
  const rows = [];
  for (const s of students) {
    const r = await resultForStudent(s.id, academicYear);
    if (r && r.marks.length) rows.push(r);
  }
  rows.sort(
    (a, b) =>
      b.average - a.average ||
      b.total - a.total ||
      studentName(a.student).localeCompare(studentName(b.student)),
  );
  let lastAvg = null,
    lastTotal = null,
    rank = 0;
  rows.forEach((r, i) => {
    if (lastAvg !== r.average || lastTotal !== r.total) rank = i + 1;
    r.rank = rank;
    lastAvg = r.average;
    lastTotal = r.total;
  });
  return rows;
}
const grades = [
  "KG 1",
  "KG 2",
  "KG 3",
  "KG 4",
  ...Array.from({ length: 12 }, (_, i) => `Grade ${i + 1}`),
];
const allowedStatuses = ["Pending", "Approved", "Rejected", "Cancelled"];
const storage = multer.diskStorage({
  destination: (_req, _file, cb) => cb(null, uploadDir),
  filename: (_req, file, cb) =>
    cb(
      null,
      `${Date.now()}-${Math.random().toString(36).slice(2)}${path.extname(file.originalname)}`,
    ),
});
const upload = multer({ storage, limits: { fileSize: 5 * 1024 * 1024 } });
app.set("trust proxy", 1);
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(
  session({
    secret:
      process.env.SESSION_SECRET || "replace-this-with-a-long-random-secret",
    resave: false,
    saveUninitialized: false,
    cookie: {
      httpOnly: true,
      sameSite: "lax",
      secure: process.env.NODE_ENV === "production",
      maxAge: 8 * 60 * 60 * 1000,
    },
  }),
);
app.use("/uploads", express.static(uploadDir));
app.use(express.static(path.join(ROOT, "public")));
function auth(req, res, next) {
  if (req.session.user) return next();
  return res.status(401).json({ error: "Authentication required" });
}
function wrap(fn) {
  return (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
}
function csvResponse(res, rows, filename) {
  const headers = Object.keys(
    rows[0] || { Registration_ID: "Registration ID" },
  );
  const esc = (v) => `"${String(v ?? "").replaceAll('"', '""')}"`;
  const csv = [
    headers.join(","),
    ...rows.map((r) => headers.map((h) => esc(r[h])).join(",")),
  ].join("\n");
  res.setHeader("Content-Type", "text/csv; charset=utf-8");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
  res.send("\uFEFF" + csv);
}

app.get(
  "/api/health",
  wrap(async (_req, res) => {
    const r = await pool.query(
      "SELECT current_database() AS db, (SELECT COUNT(*)::int FROM students) AS students",
    );
    res.json({
      ok: true,
      database: "postgres",
      db: r.rows[0].db,
      students: r.rows[0].students,
    });
  }),
);
app.post(
  "/api/login",
  wrap(async (req, res) => {
    const { username, password } = req.body || {};
 const expectedUser = process.env.ADMIN_USERNAME || "admin";
const expectedPass = process.env.ADMIN_PASSWORD;
if (!expectedPass) {
  return res
    .status(500)
    .json({ error: "Admin password is not configured" });
}
    if (username !== expectedUser || password !== expectedPass)
      return res.status(401).json({ error: "Invalid username or password" });
    req.session.user = { username: expectedUser, role: "admin" };
    res.json({ ok: true, user: req.session.user });
  }),
);
app.post("/api/logout", (req, res) =>
  req.session.destroy(() => res.json({ ok: true })),
);
app.get("/api/me", (req, res) => res.json({ user: req.session.user || null }));
app.get(
  "/api/options",
  auth,
  wrap(async (_req, res) => {
    const s = await pool.query("SELECT * FROM subjects ORDER BY name");
    res.json({
      grades,
      subjects: s.rows.map((x) => x.name),
      academic_years: yearList(),
      statuses: allowedStatuses,
      current_academic_year: currentAcademicYear(),
    });
  }),
);

app.get(
  "/api/students/:id",
  auth,
  wrap(async (req, res) => {
    const r = await pool.query("SELECT * FROM students WHERE id=$1", [
      req.params.id,
    ]);
    if (!r.rowCount)
      return res.status(404).json({ error: "Student not found" });
    res.json(r.rows[0]);
  }),
);

app.get(
  "/api/students",
  auth,
  wrap(async (req, res) => {
    const conditions = [];
    const values = [];

    if (req.query.grade) {
      values.push(req.query.grade);
      conditions.push(`grade = $${values.length}`);
    }

    if (req.query.status) {
      values.push(req.query.status);
      conditions.push(`status = $${values.length}`);
    }

    if (req.query.q) {
      values.push(`%${req.query.q}%`);
      conditions.push(
        `(first_name ILIKE $${values.length} OR middle_name ILIKE $${values.length} OR last_name ILIKE $${values.length} OR registration_id ILIKE $${values.length} OR phone ILIKE $${values.length} OR email ILIKE $${values.length})`,
      );
    }

    const where = conditions.length ? `WHERE ${conditions.join(" AND ")}` : "";

    const result = await pool.query(
      `SELECT * FROM students ${where} ORDER BY grade, last_name, first_name`,
      values,
    );

    res.json(result.rows);
  }),
);

const studentFields = [
  "registration_id",
  "first_name",
  "middle_name",
  "last_name",
  "gender",
  "date_of_birth",
  "grade",
  "program",
  "academic_year",
  "admission_date",
  "phone",
  "email",
  "address",
  "guardian_name",
  "guardian_phone",
  "status",
  "photo",
  "document",
  "notes",
];
app.post(
  "/api/students",
  auth,
  upload.fields([
    { name: "photo", maxCount: 1 },
    { name: "document", maxCount: 1 },
  ]),
  wrap(async (req, res) => {
    const b = req.body || {};
    if (!b.first_name || !b.last_name || !b.gender || !b.grade)
      return res.status(400).json({
        error: "First name, last name, gender and grade are required",
      });
    const photo = req.files?.photo?.[0]?.filename || b.photo || null,
      document = req.files?.document?.[0]?.filename || b.document || null;
    const reg = b.registration_id || (await nextRegistrationId());
    const vals = [
      reg,
      b.first_name,
      b.middle_name || null,
      b.last_name,
      b.gender,
      b.date_of_birth || null,
      b.grade,
      b.program || null,
      b.academic_year || currentAcademicYear(),
      b.admission_date || new Date().toISOString().slice(0, 10),
      b.phone || null,
      b.email || null,
      b.address || null,
      b.guardian_name || null,
      b.guardian_phone || null,
      b.status || "Pending",
      photo,
      document,
      b.notes || null,
    ];
    const cols = studentFields.join(",");
    const placeholders = vals.map((_, i) => `$${i + 1}`).join(",");
    const r = await pool.query(
      `INSERT INTO students(${cols}) VALUES(${placeholders}) RETURNING *`,
      vals,
    );
    await log("Student registered", `${studentName(r.rows[0])} (${reg})`);
    res.status(201).json(r.rows[0]);
  }),
);
app.put(
  "/api/students/:id",
  auth,
  upload.fields([
    { name: "photo", maxCount: 1 },
    { name: "document", maxCount: 1 },
  ]),
  wrap(async (req, res) => {
    const old = await pool.query("SELECT * FROM students WHERE id=$1", [
      req.params.id,
    ]);
    if (!old.rowCount)
      return res.status(404).json({ error: "Student not found" });
    const b = req.body || {},
      s = old.rows[0];
    const vals = studentFields.map((k) => {
      if (k === "photo")
        return req.files?.photo?.[0]?.filename || b.photo || s.photo;
      if (k === "document")
        return req.files?.document?.[0]?.filename || b.document || s.document;
      if (k === "registration_id") return b[k] || s[k];
      return b[k] !== undefined ? b[k] : s[k];
    });
    const set = studentFields.map((k, i) => `${k}=$${i + 1}`).join(",");
    vals.push(req.params.id);
    const r = await pool.query(
      `UPDATE students SET ${set},updated_at=CURRENT_TIMESTAMP WHERE id=$${vals.length} RETURNING *`,
      vals,
    );
    await log("Student updated", studentName(r.rows[0]));
    res.json(r.rows[0]);
  }),
);
app.patch(
  "/api/students/:id/status",
  auth,
  wrap(async (req, res) => {
    const status = req.body?.status;
    if (!allowedStatuses.includes(status))
      return res.status(400).json({ error: "Invalid status" });
    const r = await pool.query(
      "UPDATE students SET status=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 RETURNING *",
      [status, req.params.id],
    );
    if (!r.rowCount)
      return res.status(404).json({ error: "Student not found" });
    await log(
      "Student status changed",
      `${studentName(r.rows[0])} — ${status}`,
    );
    res.json(r.rows[0]);
  }),
);
app.delete(
  "/api/students/:id",
  auth,
  wrap(async (req, res) => {
    const r = await pool.query("DELETE FROM students WHERE id=$1 RETURNING *", [
      req.params.id,
    ]);
    if (!r.rowCount)
      return res.status(404).json({ error: "Student not found" });
    await log("Student deleted", studentName(r.rows[0]));
    res.json({ ok: true });
  }),
);
app.get(
  "/api/mark-students",
  auth,
  wrap(async (req, res) => {
    const vals = [],
      where = [];
    if (req.query.grade) {
      vals.push(req.query.grade);
      where.push(`grade=$${vals.length}`);
    }
    if (req.query.search) {
      vals.push(`%${req.query.search}%`);
      where.push(
        `(registration_id ILIKE $${vals.length} OR first_name ILIKE $${vals.length} OR last_name ILIKE $${vals.length})`,
      );
    }
    const r = await pool.query(
      `SELECT * FROM students ${where.length ? "WHERE " + where.join(" AND ") : ""} ORDER BY grade,last_name,first_name`,
      vals,
    );
    res.json(r.rows);
  }),
);
app.get(
  "/api/marks",
  auth,
  wrap(async (req, res) => {
    const vals = [],
      where = [];
    if (req.query.academic_year) {
      vals.push(req.query.academic_year);
      where.push(`m.academic_year=$${vals.length}`);
    }
    if (req.query.grade) {
      vals.push(req.query.grade);
      where.push(`m.grade=$${vals.length}`);
    }
    if (req.query.student_id) {
      vals.push(req.query.student_id);
      where.push(`m.student_id=$${vals.length}`);
    }
    const r = await pool.query(
      `SELECT m.*,s.registration_id,s.first_name,s.middle_name,s.last_name FROM marks m JOIN students s ON s.id=m.student_id ${where.length ? "WHERE " + where.join(" AND ") : ""} ORDER BY m.academic_year DESC,m.grade,s.last_name,m.subject`,
      vals,
    );
    res.json(r.rows);
  }),
);
app.post(
  "/api/marks",
  auth,
  wrap(async (req, res) => {
    const b = req.body || {},
      studentR = await pool.query("SELECT * FROM students WHERE id=$1", [
        b.student_id,
      ]);
    const student = studentR.rows[0];
    if (!student) return res.status(404).json({ error: "Student not found" });
    const score = Number(b.score),
      max = Number(b.max_score || 100);
    if (
      !b.academic_year ||
      !b.subject ||
      !Number.isFinite(score) ||
      score < 0 ||
      max <= 0 ||
      score > max
    )
      return res.status(400).json({
        error: "Academic year, subject and a valid score are required.",
      });
    await pool.query(
      `INSERT INTO marks(student_id,academic_year,grade,subject,score,max_score,remark,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,CURRENT_TIMESTAMP) ON CONFLICT(student_id,academic_year,subject) DO UPDATE SET grade=EXCLUDED.grade,score=EXCLUDED.score,max_score=EXCLUDED.max_score,remark=EXCLUDED.remark,updated_at=CURRENT_TIMESTAMP`,
      [
        student.id,
        b.academic_year,
        student.grade,
        b.subject,
        score,
        max,
        b.remark || "",
      ],
    );
    await log(
      "Yearly mark saved",
      `${studentName(student)} — ${b.subject} (${b.academic_year})`,
    );
    res.json({
      ok: true,
      result: await resultForStudent(student.id, b.academic_year),
    });
  }),
);
app.delete(
  "/api/marks/:id",
  auth,
  wrap(async (req, res) => {
    const r = await pool.query("DELETE FROM marks WHERE id=$1 RETURNING *", [
      req.params.id,
    ]);
    if (!r.rowCount) return res.status(404).json({ error: "Mark not found" });
    await log(
      "Yearly mark deleted",
      `Mark ${r.rows[0].subject} (${r.rows[0].academic_year})`,
    );
    res.json({ ok: true });
  }),
);
app.get(
  "/api/marks/report/:studentId",
  auth,
  wrap(async (req, res) => {
    const sr = await pool.query("SELECT * FROM students WHERE id=$1", [
      req.params.studentId,
    ]);
    if (!sr.rowCount)
      return res.status(404).json({ error: "Student not found" });
    const rows = (
      await pool.query(
        "SELECT * FROM marks WHERE student_id=$1 ORDER BY academic_year DESC,subject",
        [req.params.studentId],
      )
    ).rows;
    const years = [...new Set(rows.map((x) => x.academic_year))];
    const out = [];
    for (const year of years) {
      const r = await resultForStudent(sr.rows[0].id, year),
        ranked = await rankedResults(year, sr.rows[0].grade),
        me = ranked.find((x) => String(x.student.id) === String(sr.rows[0].id));
      out.push({ ...r, rank: me?.rank || null, class_size: ranked.length });
    }
    res.json({ student: sr.rows[0], years: out });
  }),
);
app.get(
  "/api/results",
  auth,
  wrap(async (req, res) => {
    const academic_year = req.query.academic_year || currentAcademicYear(),
      grade = req.query.grade || "";
    res.json({
      academic_year,
      grade,
      rows: await rankedResults(academic_year, grade),
    });
  }),
);
app.get(
  "/api/student-results/:id",
  auth,
  wrap(async (req, res) => {
    const sr = await pool.query("SELECT * FROM students WHERE id=$1", [
      req.params.id,
    ]);
    if (!sr.rowCount)
      return res.status(404).json({ error: "Student not found" });
    const years = (
        await pool.query(
          "SELECT DISTINCT academic_year FROM marks WHERE student_id=$1 ORDER BY academic_year DESC",
          [req.params.id],
        )
      ).rows.map((x) => x.academic_year),
      history = [];
    for (const y of years) {
      const r = await resultForStudent(sr.rows[0].id, y),
        ranked = await rankedResults(y, sr.rows[0].grade),
        me = ranked.find((x) => String(x.student.id) === String(sr.rows[0].id));
      history.push({ ...r, rank: me?.rank || null, class_size: ranked.length });
    }
    res.json({ student: sr.rows[0], history });
  }),
);
app.get(
  "/api/report-card/:studentId",
  auth,
  wrap(async (req, res) => {
    const sr = await pool.query("SELECT * FROM students WHERE id=$1", [
      req.params.studentId,
    ]);
    if (!sr.rowCount)
      return res.status(404).json({ error: "Student not found" });
    const s = sr.rows[0],
      year =
        req.query.academic_year || s.academic_year || currentAcademicYear(),
      r = await resultForStudent(s.id, year),
      ranked = await rankedResults(year, s.grade),
      me = ranked.find((x) => String(x.student.id) === String(s.id));
    res.json({
      ...r,
      rank: me?.rank || null,
      class_size: ranked.length,
      school: "KING ACADEMY SCHOOL",
    });
  }),
);

app.get(
  "/api/dashboard",
  auth,
  wrap(async (_req, res) => {
    const [studentsResult, gradesResult, recentResult, activitiesResult] =
      await Promise.all([
        pool.query(`
          SELECT
            COUNT(*)::int AS total,
            COUNT(*) FILTER (WHERE LOWER(status) = 'approved')::int AS approved,
            COUNT(*) FILTER (WHERE LOWER(status) = 'pending')::int AS pending,
            COUNT(*) FILTER (WHERE LOWER(status) = 'rejected')::int AS rejected
          FROM students
        `),
        pool.query(`
          SELECT grade, COUNT(*)::int AS count
          FROM students
          GROUP BY grade
        `),
        pool.query(`
          SELECT *
          FROM students
          ORDER BY created_at DESC, id DESC
          LIMIT 5
        `),
        pool.query(`
          SELECT *
          FROM activity_logs
          ORDER BY created_at DESC, id DESC
          LIMIT 10
        `),
      ]);

    const stats = {
      total: studentsResult.rows[0].total,
      approved: studentsResult.rows[0].approved,
      pending: studentsResult.rows[0].pending,
      rejected: studentsResult.rows[0].rejected,
    };

    const byGrade = gradesResult.rows.sort(
      (a, b) => gradeSortValue(a.grade) - gradeSortValue(b.grade),
    );

    const topAcademic = (await rankedResults(currentAcademicYear()))
      .slice(0, 5)
      .map((r) => ({
        ...r,
        student: {
          ...r.student,
          name: studentName(r.student),
        },
      }));

    res.json({
      stats,
      byGrade,
      recent: recentResult.rows,
      topAcademic,
      activities: activitiesResult.rows,
    });
  }),
);

app.get(
  "/api/export.csv",
  auth,
  wrap(async (_req, res) => {
    const r = await pool.query(
      "SELECT registration_id,first_name,middle_name,last_name,gender,date_of_birth,grade,program,academic_year,admission_date,phone,email,address,guardian_name,guardian_phone,status,created_at FROM students ORDER BY id DESC",
    );
    csvResponse(res, r.rows, "king-academy-students.csv");
  }),
);
app.get(
  "/api/export-marks.csv",
  auth,
  wrap(async (req, res) => {
    const rows = (
      await rankedResults(
        req.query.academic_year || currentAcademicYear(),
        req.query.grade || "",
      )
    ).map((x) => ({
      registration_id: x.student.registration_id,
      student_name: studentName(x.student),
      grade: x.student.grade,
      academic_year: x.academic_year,
      total: x.total,
      max_total: x.max_total,
      average: x.average,
      rank: x.rank,
      result: x.result,
      subjects: x.subjects_count,
    }));
    csvResponse(res, rows, "king-academy-yearly-results.csv");
  }),
);
app.get(
  "/api/export-subject-marks.csv",
  auth,
  wrap(async (_req, res) => {
    const r = await pool.query(
      `SELECT s.registration_id,concat_ws(' ',s.first_name,s.last_name) AS student_name,s.grade,m.academic_year,m.subject,m.score,m.max_score,ROUND((m.score*100.0/NULLIF(m.max_score,0))::numeric,2) AS percentage,m.remark FROM marks m JOIN students s ON s.id=m.student_id ORDER BY s.grade,s.last_name,s.first_name,m.academic_year,m.subject`,
    );
    csvResponse(res, r.rows, "king-academy-subject-marks.csv");
  }),
);
app.get("*", (req, res) =>
  res.sendFile(path.join(ROOT, "public", "index.html")),
);
app.use((err, _req, res, _next) => {
  console.error(err);
  if (err instanceof multer.MulterError)
    return res.status(400).json({ error: err.message });
  if (err.code === "23505")
    return res
      .status(409)
      .json({ error: "A record with this unique value already exists." });
  res.status(500).json({ error: "Server error. Check server logs." });
});
initDb()
  .then(() =>
    app.listen(PORT, () =>
      console.log(`King Academy PostgreSQL server running on port ${PORT}`),
    ),
  )
  .catch((err) => {
    console.error("Database initialization failed:", err.message);
    process.exit(1);
  });
